Sprint 1/step 2
AKatryukhin/Stellar-Burgers pull request #4
Opened 2022-01-13 08:34 UTC by AKatryukhin

2022-01-13 20:56 UTC, grishbar requested changes
В целом прекрасная работа, очень круто, что подключил erroBoundary и eslint. Хорошо, что вынес в константы и назвал в SNAKE_CASE переменные для запроса и клавишу эскейп, это очень хорошая практика. Есть несколько моментов, которые надо исправить для принятия работы:

- [ ] Этап все таки называется - “Проект. Написать весь JSX и сверстать” , так, что давай все компоненты сделаем с расширением .jsx
- [ ] Добавить обработку успешности запроса
- [ ] Переименовать не совсем удачно названные переменные
- [ ] Убрать неоправданный дизейблинг линтовых правил

2022-01-13 20:56 UTC, grishbar commented on README.md
> +
`отлично`
прикольное решение с документированием этапов 👍

2022-01-13 20:56 UTC, grishbar commented on src/components/app/app.js
> +  }, []);
`можно лучше `
это спорный вопрос, и у меня нету объективных и явных аргументов,  но на мой взгляд, использование async await лучше избегать и не использовать без необходимости, давай сделаем на callbackах при помощи .then и .catch в данном случае получится намного чище и читаемей

2022-01-13 20:56 UTC, grishbar commented on src/components/burger-constructor/burger-constructor.js
> +        <Modal isOpen={isModalOpen} title='' onClose={onModalClose}>
`можно лучше`
зачем передаешь пустую пропсу title? если не нужна, то надо удалить

2022-01-13 20:56 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.js
> +  data,
`надо исправить`
старайся избегать таких абстрактных названий переменных, как data, совсем непонятно, что лежит в ней, дай ей какое нибудь понятное имя, которое явно говорит, что лежит в твоей переменной

2022-01-13 20:56 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.js
>    const bread = data.filter((i) => i.type === 'bun');
`можно лучше`
кажется это все таки buns а не bread

2022-01-13 20:56 UTC, grishbar commented on src/components/burger-ingredients/burger-ingredients.js
>    const main = data.filter((i) => i.type === 'main');
`можно лучше`
все массивы должны быть во множественном числе, так сразу понятно, что в этих переменных лежат массивы (sauces, mains)

2022-01-13 20:56 UTC, grishbar commented on src/components/error-boundary/error-boundary.js
> +export class ErrorBoundary extends Component {
`отлично`
круто, что подключил errorboundary на проект, эту библиотеку довольно часто используют в крупныз проектах в том числе в больших компаниях, умение работать с ней хороший + тебе)

2022-01-13 20:56 UTC, grishbar commented on src/components/ingredients-list/ingredients-list.js
> +  const handleListItemClick = useCallback((item) => onModalOpen(item), []);
`надо исправить`
для чего тут дизейблишь eslint? 
кажется ты тут не вызовешь лишних ререндеров, если избавишься от дизейблинга и добавишь onModalOpen в заависимости, а вот баг, при таком виде словить можешь

2022-01-13 20:56 UTC, grishbar commented on src/components/order-details/order-details.js
> +      </p>
`можно лучше`
кажется тут, немного опечатался, зачем то везде в классы положил text="true"

2022-01-13 20:56 UTC, grishbar commented on src/components/app/app.js
> +        });
`надо исправить`
тут надо обработать статус ответа, [response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok), так как у тебя может запрос выполниться, но вернуться с ошибкой, и тут нужно проверить, что запрос выполнился успешно, соотвественно если нет, то выкинуть ошибку, чтобы попасть в блок catch

2022-01-14 09:01 UTC, AKatryukhin commented
Привет.  Исправил все недочеты в соответствии с комментариями. Есть только момент насчет async/await. Я сделал в двух вариантах (код с then рабочий, но пока я его закомментировал). Если возможно, то оставил бы с async/await, мне так удобней.

2022-01-14 09:03 UTC, AKatryukhin commented
Привет. Спасибо за ревью! Все замечания справедливы и по делу. Исправил все недочеты в соответствии с комментариями. Есть только момент насчет async/await. Я сделал в двух вариантах (код с then рабочий, но пока я его закомментировал). Если возможно, то оставил бы с async/await, мне так удобней.

2022-01-14 11:25 UTC, grishbar approved these changes
Отлично, все критичные ошибки исправлены, работу принимаю, удачи в дальнейшем обучении!)

2022-01-14 11:25 UTC, grishbar commented on src/components/app/app.jsx
> +  //  // eslint-disable-next-line react-hooks/exhaustive-deps
`можно лучше`
если тебе async await удобнее оставь так, обычно на проектах есть негласное правило, что стараются использовать. Этот задокументированнй код удали, должны оставаться только комментарии документирующие код

2022-01-14 11:41 UTC, merged